debug : true

# cache
cache.options :
  default :
    driver : filesystem
    directory : ../cache/

# twig
twig.path : ../src/Views
twig.options :
  cache : false

# models repository
models_repository.options:
  namespace: Models
